server:
  port: 8000
#spring:
#  mvc:
#    view:
#      prefix: /page/
#      suffix: .html
com:
  star:
    webssh:
      web-socket-handler: /webssh
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.63.188.39:3306/ssh_project?user=root&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: '@KunKun2023'
  redis:
    host: 116.63.188.39
    port: 6379
    password: '@KunKun2023'
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
