server:
  port: 8000
#spring:
#  mvc:
#    view:
#      prefix: /page/
#      suffix: .html
com:
  star:
    webssh:
      web-socket-handler: /webssh
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssh?user=root
    username: root
    password: 123s123S@

mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
